### ISSUE TITLE
Could you tell me how to set the login account password, please?

### ISSUE THREAD

**Issue by Skinsly** [glanceapp/glance#280] opened 2024-12-15 10:11 UTC
Could you tell me how to set the login account password, please?

**Comment by svilenmarkov** [comment] 2024-12-15 14:35
Hey, that kind of functionality currently does not exist. I suppose the reason for this is that Glance was built with public feeds in mind and the few extensions that allow you to expose other kinds of data are fairly harmless. 

If you have custom widgets that display more sensitive information you can easily add your own authentication via something like [basic auth if you have Glance running behind nginx](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/), [Authelia](https://github.com/authelia/authelia) or [Authentik](https://github.com/goauthentik/authentik) depending on your needs.

I'll close this since it's a duplicate of #103 and will reconsider adding this later down the line if it gains more interest, though for the time being I see it as fairly low priority since there are ways around it.

**Closed by svilenmarkov** 2024-12-15 14:35 UTC
