### ISSUE TITLE
[Feature request] Docker container service status (e.g., 'healthy') vs., ping in monitor widget

### ISSUE THREAD

**Issue by mgrimace** [glanceapp/glance#274] opened 2024-12-07 15:59 UTC
This request is to optionally show a docker container's status rather than its reachability when using the monitor widget. For example, if the monitor widget is set up for a list of docker services, ideally, the green check, 'OK', and ping could instead show whether the container is 'running', 'stopped', 'restarting', 'healthy', etc.

The use-case for this would be to see docker service statuses at-a-glance in a homelab type group.

**Comment by mnmnk43434** [comment] 2024-12-07 16:08
Hello, we tried to solve the issue.

This is what we did:

Modified the Monitor widget to optionally show Docker container status instead of just the reachability status. Updated the struct definitions, added new functions for Docker status checks, and modified the template to display the new information.

You can review changes in this commit: https://github.com/mnmnk43434/glanceapp-glance-274/commit/2081209b55179440b7a2ac13f3acb5f5f23e5c7c.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by svilenmarkov** [comment] 2024-12-07 16:36
Hey, this feature was implemented in #261 and will be available in v0.7.0. If you don't want to wait until then you can of course pull the branch and build the project yourself, though keep in mind that the documentation for that widget is not yet updated. 

Will close this since it's a duplicate of #38.

**Closed by svilenmarkov** 2024-12-07 16:36 UTC

**Comment by mgrimace** [comment] 2024-12-07 17:08
Amazing, thank you for your hard work on this!
